name: Fortify SAST (reusable)

on:
  workflow_call:
    inputs:
      app-version:
        required: false
        type: string
      runner-label:
        required: false
        type: string
        default: fortify-sast
      java-version:
        required: false
        type: string
        default: '17'
      build-tool:
        required: false
        type: string
        default: mvn
    secrets:
      SSC_TOKEN:
        required: true
      SC_SAST_TOKEN:
        required: true

jobs:
  sast:
    runs-on: [ self-hosted, "${{ inputs.runner-label }}" ]
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: Run Fortify ScanCentral SAST scan
        uses: fortify/github-action@v3
        env:
          SSC_URL: ${{ vars.SSC_URL }}
          SSC_TOKEN: ${{ secrets.SSC_TOKEN }}
          SC_SAST_TOKEN: ${{ secrets.SC_SAST_TOKEN }}
          SSC_APPVERSION: ${{ inputs.app-version }}
          DO_WAIT: true
          DO_SAST_EXPORT: true
          PACKAGE_EXTRA_OPTS: '-bt ${{ inputs.build-tool }}'
          SSC_LOGIN_EXTRA_OPTS: '--insecure'
          SC_SAST_LOGIN_EXTRA_OPTS: '--insecure'
